site_name: maxup
site_description: Deploy static websites quickly and easily to AWS S3!
theme:
  name: material
  palette:
    primary: 'green'
    accent: 'green'
copyright: Copyright &copy; 2018 Filiosoft, LLC
site_author: Filiosoft, LLC
repo_url: https://github.com/filiosoft/maxup/
pages:
  - Intro: index.md
  - The CLI: cli.md
  - The API: 
    - API Basics: api.md
    - Endpoints: api/endpoints.md